<!-- begin content -->
<div class="row app-container">
    <div class="one-half column">
        <h3><?= $this->title ?></h3>
        <p>
            This index.html page is a placeholder with the CSS, font and favicon. 
            It's just waiting for you to add some content! If you need 
            some help hit up the <a href="http://www.getskeleton.com">Skeleton documentation</a>.
        </p>
    </div>
</div>
<!-- end content -->