<!-- begin content -->
<div class="row app-container">
    <div class="row">
        <div class="column">
            <a class="button button-primary" onclick="window.history.back()">Back</a>
        </div>
    </div>
    <div class="row">
        <div class="column">
            <h1>Create Book</h1>
            <form method="post" action="/ebook/create" enctype="multipart/form-data">
                <div class="row">
                    <div class="column">
                        <label for="author">Author</label>
                        <input class="u-full-width" type="text" id="author" name="author">
                    </div>
                </div>
                <div class="row">
                    <div class="column">
                        <label for="file">Import PDF Book</label>
                        <input class="u-full-width" type="file" id="file" name="file">
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="column">
                        <input class="button-primary" type="submit" value="Submit">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- end content -->