<?php
$books          = $this->books;
$errorCode      = $this->errorCode;


$messageError = null;

if($errorCode === "upload_error"){
    $messageError = "Error al subir el archivo";
}else if($errorCode == Book::IMPORT_ERROR_COMMAND){
    $messageError = "Error al convertir el documento pdf";
}else if($errorCode == Book::IMPORT_ERROR_TO_GET_PDF_INFORMATION){
    $messageError = "Error obtener información del documento pdf";
}
?>
<!-- begin content -->
<div class="row app-container">
    <?php
    if($messageError){
        ?>
        <h5><?= $messageError ?></h5>
        <?php
    }
    ?>
    <div class="row">
        <div class="column">
            <a class="button button-primary" href="/ebook/create">Create</a>
        </div>
    </div>
    <div class="row">
        <div class="column">
            <h1>Books</h1>
            <table class="u-full-width news-list">
                <thead>
                    <tr>
                        <th>bookId</th>
                        <th>Author</th>
                        <th>Options</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if($books){
                        foreach ($books as $book){
//                            $book = new Book();
                            ?>
                            <tr>
                                <td>
                                    <?= $book->getBookId() ?>
                                </td>
                                <td>
                                    <?= $book->getAuthor() ?>
                                </td>
                                <td>
                                    <a href="/ebook/<?= $book->getBookId() ?>" target="_blank">Ver Ebook</a>
                                </td>
                            </tr>    
                            <?php
                        }
                    }else{
                        ?>
                        <tr>
                            <td colspan="3">
                                No hay libros por mostrar...
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- end content -->