<?php
$book = $this->book;

//$book = new Book();

$entryPath          = __PATH__ . "/public/resources/ebook/{$book->getBookId()}";
$entryPublicPath    = "/resources/ebook/{$book->getBookId()}";

$PDFpath = array_pop(glob("{$entryPath}/*.pdf"));

/*
 * Get PDF information
 */
$pdfInfo = PDF_get_information($PDFpath);

?>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title><?= $this->pageTitle ?></title>
        <meta name="description" content="App description">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <!--favicon-->
        <link rel="shortcut icon" type="image/ico" href="/resources/image/favicon.ico">
        <!--css files-->
        <link href="https://file.myfontastic.com/6MxRKou359wj5rQPH9Xfgc/icons.css" rel="stylesheet">
        <link rel="stylesheet" href="/css/normalize.css">
        <link rel="stylesheet" href="/css/skeleton.css">
        <link rel="stylesheet" href="/css/general-responsive.css">
        <link rel="stylesheet" href="/js/vendor/turnjs/magazine.css">
        <link rel="stylesheet" href="/js/vendor/colorpicker/colorPicker.css">
        <!--js files-->
        <script src="/js/vendor/jquery-2.1.1.min.js"></script>
    </head>
    <body>
        <div class="container u-full-width u-max-full-width">
            <!--Navigation-->
            <div class="nav">
                <div class="row">
                    <div class="four columns factory-logo">
                        OWL Editorial
                    </div>
                    <div class="four columns navbar">
                        <div class="icon first">
                            <i class="icon-previous"></i>
                        </div>
                        <div class="icon previous">
                            <i class="icon-rewind"></i>
                        </div>
                        <div class="navbar-paginator">
                            <input type="text" data-current-page value="1">
                            / <?= $pdfInfo->pages ?>
                        </div>
                        <div class="icon next">
                            <i class="icon-fast-forward"></i>
                        </div>
                        <div class="icon last">
                            <i class="icon-next"></i>
                        </div>
                    </div>
                    <div class="four columns toolbar">
                        <div class="icon zoom-in">
                            <i class="icon-zoom-in"></i>
                        </div>
                        <div class="icon zoom-out">
                            <i class="icon-zoom-out"></i>
                        </div>
                        <div class="icon clipboard">
                            <i class="icon-clipboard-pencil"></i>
                        </div>
                        <div class="icon slider">
                            <i class="icon-thumbnails"></i>
                        </div>
                        <div class="icon zoom">
                            <i class="icon-arrows-expand"></i>
                        </div>
                    </div>
                </div>
                <div class="switch">
                    <div class="switch-button">
                        <i class="icon-triangle-up"></i>
                    </div>
                </div>
            </div>
            <!--Viewport-->
            <div class="magazine-viewport">
                <div class="container">
                    <div class="magazine">
                        <!-- Next button -->
                        <div ignore="1" class="next-button"></div>
                        <!-- Previous button -->
                        <div ignore="1" class="previous-button"></div>
                    </div>
                </div>
            </div>
            <!-- Thumbnails -->
            <div class="thumbnails">
                <div class="controls">
                    <div class="option left">
                        <i class="icon-chevron-left"></i>
                    </div>
                    <div class="option right">
                        <i class="icon-chevron-right"></i>
                    </div>
                </div>
                <div class="content">
                    <ul>
                        <?php
                        for($i = 1; $i <= $pdfInfo->pages; $i++){
                            ?>
                            <li data-page="<?= $i ?>">
                                <img>
                                <span><?= $i ?></span>
                            </li>
                            <?php
                        }
                        ?>
                    </ul>
                </div>	
            </div>
        </div>
        <!--notes-->
        <div id="note">
            <div class="row">
                <div class="note">
                    <div class="note-controls">
                        <button type="button" class="close">
                            <i class="icon-arrows-compress"></i>
                        </button>
                    </div>
                    <h4>Crear nueva nota</h4>
                    <div class="note-form">
                        <form>
                            <input type="hidden" name="page">
                            <textarea name="description"></textarea>
                            <span>Seleccionar color</span>
                            <input id="color-picker" type="text" name="color" value="#FFE459">
                            <div class="u-cf"></div>
                            <button type="submit">
                                <i class="icon-pencil"></i> Guardar nota
                            </button>
                        </form>
                    </div>
                    <h4>Mis notas</h4>
                    <div class="note-container"></div>
                </div>
            </div>
            <!--template-->
            <div class="template" id="note-item-template">
                <div class="item">
                    <div class="visible">
                        <div class="description"></div>
                        <div class="controls">
                            <button type="button" class="edit">
                                Editar
                            </button>
                            <button type="button" class="delete">
                                Eliminar
                            </button>
                        </div>
                    </div>
                    <div class="hidden">
                        <form>
                            <button type="submit" class="save">
                                Guardar
                            </button>
                            <button type="button" class="cancel">
                                Cancelar
                            </button>
                            <textarea name="description"></textarea>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <script src="/js/vendor/modernizr-2.8.3.min.js"></script>
        <script src="/js/vendor/jquery.mousewheel.min.js"></script>
        <script src="/js/vendor/colorpicker/jquery.colorPicker.js"></script>
        <script src="/js/plugins.js"></script>
        <script src="/js/vendor/turnjs/main.js"></script>
        <script src="/js/vendor/turnjs/hash.js"></script>
        <script type="text/javascript">
            /*
             * Set global vars
             */
            var book = {
                id          : <?= $book->getBookId() ?>,
                pages       : <?= $pdfInfo->pages ?>,
                pageWidth   : <?= $pdfInfo->size->width ?>,
                pageHeight  : <?= $pdfInfo->size->height ?>,
                path        : "<?= $entryPublicPath ?>"
            };
            
            // Load the HTML4 version if there's not CSS transform
            yepnope({
                test: window.Modernizr.csstransforms,
                yep : ['/js/vendor/turnjs/turn.js'],
                nope: ['/js/vendor/turnjs/turn.html4.js'],
                both: [
                    '/js/vendor/turnjs/zoom.js', 
                    '/js/vendor/turnjs/magazine.core.js'
                ],
                complete: window.initApp
            });
        </script>
    </body>
</html>